// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/////////....
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return macos;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAIDSjgg0vMXMpquml2DwMo1dpCmfq4fv0',
    appId: '1:931238830014:web:6e125d43245d94bb2fe3ef',
    messagingSenderId: '931238830014',
    projectId: 'chec-events-584ad',
    authDomain: 'chec-events-584ad.firebaseapp.com',
    storageBucket: 'chec-events-584ad.appspot.com',
    measurementId: 'G-21EVMHGT32',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBwq8Nvf0afcgsrykOfqjJIv7_vTwNbZ0E',
    appId: '1:931238830014:android:846dafc067e9b67d2fe3ef',
    messagingSenderId: '931238830014',
    projectId: 'chec-events-584ad',
    storageBucket: 'chec-events-584ad.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAz_RmBr0x2AuLfcthIwh0dZ2oa6YRII_Y',
    appId: '1:931238830014:ios:d94bd852aeb905042fe3ef',
    messagingSenderId: '931238830014',
    projectId: 'chec-events-584ad',
    storageBucket: 'chec-events-584ad.appspot.com',
    iosBundleId: 'com.example.chicEvents',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAz_RmBr0x2AuLfcthIwh0dZ2oa6YRII_Y',
    appId: '1:931238830014:ios:2af9a39d292be9522fe3ef',
    messagingSenderId: '931238830014',
    projectId: 'chec-events-584ad',
    storageBucket: 'chec-events-584ad.appspot.com',
    iosBundleId: 'com.example.chicEvents.RunnerTests',
  );
}
